### ISSUE TITLE
index mobile responsive

### ISSUE THREAD

**Issue by scaltro** [scaltro/jobdoneNET#1]
link : https://jobdone.net/

1. need move login and links `login` and `join` in up of page.
2. need fix search box, (search button not need to be visible ).

<img width="402" alt="screen shot 2017-07-28 at 11 30 27 pm" src="https://user-images.githubusercontent.com/12735678/28735220-ef77a4c8-73ec-11e7-9d08-3c8177fe13ed.png">

3. move on center elements on footer.

<img width="431" alt="screen shot 2017-07-28 at 11 34 27 pm" src="https://user-images.githubusercontent.com/12735678/28735331-5b15a6e4-73ed-11e7-8e9b-5dbf64b31e1b.png">

**Comment by Olezha** [comment]
this is simple task, but what at background. have you source code and accesses?

![2017-08-06 16-10-18](https://user-images.githubusercontent.com/7818007/29003584-f5eba9c2-7ac1-11e7-82ae-7f2d19a63588.png)

**Comment by Bro05** [comment]
1.
 @media only screen and (max-width: 500px){.
  header .logo{position:absolute; left:-40px;top:5px; }
  header .right{margin-top:-30px;}
 2. 
    .search_frm input[type="submit"]{display:none;}
  .search_frm input[type="search"]{border-radius:4px 4px 4px 4px; position:fixed; left:22%;}
 3.
 Can't reproduce bug

**Comment by Bro05** [comment]
.search_frm input[type="submit"]{display:none;}
  .search_frm input[type="search"]{border-radius:4px 4px 4px 4px; position:fixed; left:17%;}
  .hdr_bnr_content {height:auto;}
