### ISSUE TITLE
mobile-seller service page

### ISSUE THREAD

**Issue by angelo121290** [scaltro/jobdoneNET#11]
(https://user-images.githubusercontent.com/25940674/28738593-08989a06-73fd-11e7-9f6e-0ed57f0a3caf.jpg)
need make visible SERVICE | PUBLISHED ON | VIEWS | ORDERS | ACTIONS https://jobdone.net/account/seller/services

**Comment by Bro05** [comment]
same number 6

**Comment by Bro05** [comment]
And it's ok
