### ISSUE TITLE
mobile - filter service

### ISSUE THREAD

**Issue by scaltro** [scaltro/jobdoneNET#2]
link : https://jobdone.net/explore?

need fix filter services on mobile navigation.
on mobile navigation after enable the menu `FILTER ON` same elements is wrong display : 

(https://user-images.githubusercontent.com/12735678/28735616-c1822c30-73ee-11e7-984b-ed42295a72d8.png)

need fix

**Comment by Bro05** [comment]
frontend/style/main.scss
.opened
  {overwrite:visible }
