### ISSUE TITLE
ipad-buyer orders

### ISSUE THREAD

**Issue by angelo121290** [scaltro/jobdoneNET#21]
(https://user-images.githubusercontent.com/25940674/28743197-87a7840c-744c-11e7-93c3-9fff31067249.png)

1.fix username under people profile image 
2.make visible things in green like "awaiting confirmation","in progress" https://jobdone.net/account/buyer

**Comment by Bro05** [comment]
fixed with same issue in seller

**Comment by Bro05** [comment]
![image](https://user-images.githubusercontent.com/3815603/29240994-60f3af60-7f79-11e7-9023-d27120166b17.png)
