### ISSUE TITLE
ipad-buyer favorites

### ISSUE THREAD

**Issue by angelo121290** [scaltro/jobdoneNET#23]
(https://user-images.githubusercontent.com/25940674/28743285-1272f3f8-744f-11e7-9f29-791563e47b9c.png)

fix and make visible title of service under image of service https://jobdone.net/account/favorites

**Comment by Bro05** [comment]
do this in webStyles.css, may be need do the same for 760px:
@media only screen and (max-width:520px) {
    .services-list.favourites .service {width:200px !important; padding:7px 7px !important;}

**Comment by Bro05** [comment]
.services-list.favourites .service {
    display: block;
    width: 263px;
    padding: 0 7px;
    height: 200px;
    float: left;
    margin: 15px;
}
.services-list.favourites .service h4 {
    margin-top: 20px;
}

**Comment by Bro05** [comment]
Done
