### ISSUE TITLE
ipad - fix menu on dashboard

### ISSUE THREAD

**Issue by scaltro** [scaltro/jobdoneNET#4]
link : https://jobdone.net/dashboard
look like is hidden half menu, and is hidden close button.

http://jmp.sh/Fuo6tmQ

corect display is this : http://jmp.sh/qHPciLN

**Comment by Bro05** [comment]
for menu opened {right:0;} - seem's that do it somebody else

**Comment by scaltro** [comment]
@Bro05 

http://jmp.sh/d6AU5co
http://jmp.sh/jBOV53N

**Comment by Bro05** [comment]
Thank you, fixed
@media (max-width:1150px) {
    header .menu.opened   {right:0;}
}
