### ISSUE TITLE
mobile-buyer page

### ISSUE THREAD

**Issue by angelo121290** [scaltro/jobdoneNET#9]
(https://user-images.githubusercontent.com/25940674/28738301-5e195562-73fb-11e7-9192-287445dcb254.jpg)

1. need fix in the center SELLER | SERVICE | ORDERED | DUE ON | TOTAL
2. need fix username under profile image https://jobdone.net/account/buyer

**Comment by Bro05** [comment]
same  with issue 6

**Comment by Bro05** [comment]
same with saller
